### ISSUE TITLE
Document reasons for changing to Mojolicious

### ISSUE THREAD

**Issue by leto** [letolabs/app-parrot-create#6]
Currently app-parrot-create uses Dancer 1.3.x, which was current at the time of it's writing. Now that Dancer is on v2, we are behind the times.

What are the benefits are migrating to Mojolicious, @denisboyun ? I am fine with it, I just don't want to do it if it doesn't buy us much. I plan on running this code under nginx/varnish, if that helps.

**Comment by dboys** [comment]
If saying about current idea - "one-page website which are generating zip files". I cann't see more benefits. One of them you can call being route and after that work with that route via name, autogenerate documentation and no external dependencies. But if we are evaluating the overall frameworks. Mojolicious are supporting websockets, ssl, html5, css3, *CGI, stash, extended perl(perl into html) and maaaaaaaany plugins.

**Comment by leto** [comment]
We are using Mojolicious and enjoying it. Closing...
