### ISSUE TITLE
PARROT_REVISION incorrect

### ISSUE THREAD

**Issue by leto** [letolabs/app-parrot-create#8]
It seems that PARROT_REVISION does not get it's variables properly interpolated

```
$ cat PARROT_REVISION 
Revision

$
```

**Comment by dboys** [comment]
What should be revision? Because I can't find any keys with name "revision" on parrot config.

**Comment by leto** [comment]
For now, set it to the minimum Parrot version required for the project. It can be an optional input value on the input form, with a default value of "5.3.0" (which is when Winxed was included in Parrot)

**Comment by dboys** [comment]
closed
https://github.com/letolabs/app-parrot-create/commit/556cf14b28d4f97abb2054641390c0d0e9f27a9d
